# .air.toml

[build]
cmd = "go build -o ./tmp/main"
args = ["-ldflags", "-s -w"]
main = "main.go"

# Additional settings
[[event]]
  # Reload .env file when it changes
  command = "cp .env ./tmp/.env"
  include_ext = ["env"]
  exclude_dir = ["tmp"]
  recursive = false
