version: '3'

name: bytetask

services:
  mongo:
    container_name: mongodb
    image: mongo:7
    restart: always
    env_file:
      - ./app.env
    ports:
      - '27017:27017'
    volumes:
      - bytefrost:/data/db
    networks:
      - bytefrost

  bytetask-api:
    container_name: bytetask-api
    image: bytetask-api:1.0.0
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - bytefrost:/app
    depends_on:
      - mongo
    networks:
      - bytefrost
    environment:
      MONGO_URL: "mongodb://mongo:27017/ssl=false&authSource=admin"
    command: go run /app/cmd/main.go -b 0.0.0.0

networks:
  bytefrost:
    name: bytefrost
    driver: bridge

volumes:
  bytefrost:
    